### ISSUE TITLE
Task 8: Notebook

### ISSUE THREAD

**Issue by Ange-Dvs** [Ange-Dvs/computer_infrastructure_assessment#8]
Create a notebook called _weather.ipynb_ at the root of your repository. In this notebook, write a brief report explaining how you completed Tasks 1 to 7. Provide short descriptions of the commands used in each task and explain their role in completing the tasks

- [x] Create the notebook
- [x] Summarise [Task 1: Create Directory Structure](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/1)
- [x] Summarise [Task 2: Timestamps](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/2)
- [x] Summarise [Task 3: Formatting Timestamps](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/3)
- [x] Summarise [Task 4: Create Timestamped Files](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/4)
- [x] Summarise [Task 5: Download Today's Weather Data](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/5)
- [x] Summarise [Task 6: Timestamp the Data](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/6)
- [x] Summarise [Task 7: Write the Script](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/7)
- [ ] Check all used commands are summarised
- [ ] Review & edit the summaries for tasks 1-7
- [ ] Finalise and tidy up the notebook
- [ ] Final commit and push

**Comment by Ange-Dvs** [comment]
- [ ] Create the notebook
- [ ] Summarise [Task 1: Create Directory Structure](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/1)
- [ ] Summarise [Task 2: Timestamps](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/2)
- [ ] Summarise [Task 3: Formatting Timestamps](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/3)
- [ ] Summarise [Task 4: Create Timestamped Files](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/4)
- [ ] Summarise [Task 5: Download Today's Weather Data](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/5)
- [ ] Summarise [Task 6: Timestamp the Data](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/6)
- [ ] Summarise [Task 7: Write the Script](https://github.com/Ange-Dvs/computer_infrastructure_assessment/issues/7)

**Comment by Ange-Dvs** [comment]
Draft of tasks 1 - 4 created in weather.ipynb.

**Comment by Ange-Dvs** [comment]
Draft of tasks 1 - 7 created in weather.ipynb
